### PR TITLE
Removed final modifier from JIComRuntimeTransport

### PR DESCRIPTION
**Pull request by DerekRushton**
For our use case we'd like to be able to extend this class and override the attach method.

### CODE REVIEW

**Comment by skyghis** [comment]
Thank you for the PR.
Can I know your use case ? It might be simpler to integrate it in the library instead of external overwrite ?

**Comment by DerekRushton** [comment]
In our case we wanted to use a java socket instead of the hardcoded socket and instead of using the JIComRuntimeEndpoint we wanted to use the ConnectionOrientedEndpoint from J-interopdeps.

If we had a way to pass in a socket and endpoint, potentially via the constructor, that would likely satisfy our use case.

**Comment by skyghis** [comment]
I can easily add a way to ease custom `socket` and `endpoint` use, I will create a branch to show my idea.

Can I know why you would need to depend on another `socket` / `endpoint` ? Your modifications / use case could be integrated in the library ?

**Comment by ChrisCollinsIBM** [comment]
> 

The `socket` itself likely wouldn't be a different implementation (but could be), but could definitely have different config parameters associated with it that you don't want to se JVM-wide (SO_TIMEOUT being a prime example).

**Comment by skyghis** [comment]
Did the solution present in branch `custom-runtime-transport` #8  is OK for you ?

**Comment by DerekRushton** [comment]
Yes, that solution seems reasonable and would accommodate our needs. I haven't had a chance to test it in our environment yet, but based off the commit it looks like it will work. I'll post an update when I've confirmed it works in our environment.

Also just want to say thanks for looking into this as promptly as you are. It's really appreciated.

**Comment by DerekRushton** [comment]
Hey, sorry about the delay. I took a deeper look at the changes you've made and tried using them in our environment, unfortunately I don't think they will work for us. After looking into the issue we can't directly access the transport. Instead it's created by the factory and we can't modify/access how said factory creates and uses the transport object it creates. We can't access (at least easily) without modifying some other code in the j-interopdeps (I'm assuming), which would defeat the point. I feel like the changes will require more effort and could break pieces of the code we can't even test. 

I'd initially assumed that our work was using the j-interop package more than it actually is. It looks like were really only using the j-interopdeps and using slightly modified versions of JIWinRegStub and JIComRuntimeTransport to create our stub and transport. If the JIComRuntimeTransport class was not final, it would still help us, however I feel that may not be needed now after discussing the issue with other people on my team. 

Again, It's really appreciated that you took the time to help out.

**Comment by skyghis** [comment]
Thanks for taking time to reply.
I closed my merge request and will include the public / not final modifications on the master branch.
I have some cleanup code change in progress. Once done, I will create a new release.

If possible, I would appreciate having more information about your use case and your modifications. Don't hesitate to PM me.

**Comment by DerekRushton** [comment]
Our use of these jars is complicated. What we've done is made use of the original J-Interopdeps base classes (under rpc and ndr) to implement our own version for windows communication. 

For this specific use case, the JIComRuntimeTransport was implementing everything we needed our transport to do except for those two small changes (socket and endpoint) and we'd prefer to extend from the class instead of copy it.

**Comment by DerekRushton** [comment]
I've made another pull request here https://github.com/skyghis/j-interop-ng/pull/9, I originally though just removing the final modifier was enough, but the constructor was still private (so I couldn't access it). That pull request is just making a few variables/methods protected instead of private and allowing the user to override the socket/endpoint.

**Pull request merged**
