### PR TITLE
Made the endpoint and socket modifiable.

### PR DESCRIPTION
**Pull request by DerekRushton**
The change to make this class extendable requires a few more modifications. We'd prefer to extend from this instead of copying the code.

### CODE REVIEW

**Comment by DerekRushton** [comment]
Hi @skyghis, I'm just wondering if you've had a chance to consider this change?

**Comment by DerekRushton** [comment]
Hey, @skyghis just asking again if you could take a look at this.

**Comment by skyghis** [comment]
Sorry for the delay, some personal task take all my time. I'll try to take a look this week.

**Comment by DerekRushton** [comment]
It's no problem. Thanks for taking a look into it for me.

**Comment by DerekRushton** [comment]
Hi again, I'm just wondering when you think you will have a new release (that includes these changes)?

**Comment by skyghis** [comment]
v3.4.0 on nexus. Might need up to 24h for the index to update.

**Comment by DerekRushton** [comment]
Good to hear. Thanks

**Pull request merged**
